### ISSUE TITLE
Require ETA of UWP

### ISSUE THREAD

**Issue by FlyingStarlight** [Tlaster/WeiPo#135]
打扰了，商店目前版本是还在2019/9/10 
看到大佬的最新commit也是今年6月底了
请问是否有更一版的计划呢？

**Comment by Tlaster** [comment]
感谢关注
这几个月都在忙着写些没前途的代码，没有太多精力维护

**Comment by FlyingStarlight** [comment]
> 感谢关注
> 这几个月都在忙着写些没前途的代码，没有太多精力维护

辛苦了，希望有空能随手编译发一下
