### ISSUE TITLE
UWP版无限崩溃

### ISSUE THREAD

**Issue by ChuHuaiJin** [Tlaster/WeiPo#66]
1.首次登录正常，在调整了窗口大小后{调整为显示一列时间线宽度}，客户端崩溃。
2.重置客户端后，再次登录会直接崩溃，再次启动会无限崩溃

Windows 10 1903

**Comment by Tlaster** [comment]
应该是#65，正在修复

**Comment by Tlaster** [comment]
更新已经提交了，等待1.1.1.0版本更新应该就好了
